Homework #1
gavrilovds/link-tracker pull request #1
Opened 2024-02-09 17:23 UTC by gavrilovds

Реализован скелет телеграмм-бота, были сделаны основные команды бота.

## Примеры команд

#### /start
<img width="378" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/0f550712-4696-4b64-bdf8-50d453f6a772">

#### /help
<img width="373" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/d726f3b0-28ef-4730-8df5-a56cada94e9c">

#### /untrack
<img width="366" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/ff0a40e4-9f97-4178-958e-c11a22c04e88">

#### /track
<img width="366" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/50b616f6-89f8-4aed-a448-fa3fa18e9fed">

#### /list
<img width="378" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/d920082c-8e19-4ac7-b363-ef1ef24225a9">

#### Также было выполнено доп. задание (создание меню команд бота)
<img width="367" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/47b66aed-4341-4aaf-b08f-67d39773834e">

2024-02-18 14:23 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/HelpCommandExecutor.java
> +        if (!command.equals(HELP.getCommandName())) {
В задании написано про Chain of responsibility, однако, ИМХО, в данном случае у конкретной команды есть конкретный обработчик. Я бы вынес отдельное поле типа Command, которое указывало бы на то, какой тип команд обрабатывает данный класс, а в CommandChain просто использовал бы мапку, где ключ - тип команды, а значение - обработчик. Так не придётся дублировать логику по проверке совпадения команды, да и сам процесс будет гораздо быстрее - O(1) вместо O(n)0.

2024-02-18 14:24 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/Command.java
> +    private final String commandName;
Префикс command избыточен, из контекста понятно, что это название и описание команды.

2024-02-18 14:30 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/LinkTrackerBot.java
> +        @Lazy UpdatesListener updatesListener
`@Lazy` - антипаттерн, который может привести к очень неприятным проблемам на проде. Лучше от него избавиться.

2024-02-18 14:33 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/BotUpdatesListener.java
> +    private final MessageSender messageSenderImpl;
`Impl` стоит убрать из названия.

2024-02-18 14:35 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/BotConfig.java
> +    public LinkService linkService() {
Класс уже помечен как сервис, можно отдельно бин не создавать, он будет создан контейнером автоматически.

2024-02-18 14:42 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/BotConfig.java
> +        return UpdateResolver.link(
Сейчас эта логика работает, потому что аннотация component есть только в абстрактном класс. Данная аннотация не наследуется, поэтому дочерние классы не создаются контейнером как бины и все ок. Вообще аннотировать таким образом абстрактные классы и интерфейсы я не советую. 

![image](https://github.com/gavrilovds/link-tracker/assets/15994914/b1bfce1d-f9a6-493e-8235-98ab7e90686e)

По поводу создания бина. Так тоже можно, но это немного сложно и в случае больших проектов очень легко просто забыть добавить сюда еще одну реализацию. Я бы предложил создать класс Manager, в который бы заинжектил список всех резолверов, после чего проставил бы цепочку.

2024-02-18 14:42 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/BotConfig.java
> +        return UpdateResolver.link(
Аналогично для других классов.

2024-02-18 14:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/keyboard_builder/KeyboardBuilder.java
> +package edu.java.bot.keyboard_builder;
Я бы просто создал пакет utils) а то на каждый билдер по пакету - так всех пакетов из пакета с пакетами не хватит.

2024-02-18 14:44 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/message_sender/MessageSender.java
> +    SendResponse sendMessage(SendMessage message);
Точно ли нужен интерфейс? Ожидается много реализаций? Да и сам класс я бы унес в сервисы.

2024-02-18 14:44 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/message_sender/MessageSenderImpl.java
> +    private final LinkTrackerBot bot;
Вот ту и возникает циклическая зависимость, да?

2024-02-18 14:44 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/message_sender/MessageSenderImpl.java
> +        log.info("Response is Ok: {}", response.isOk());
Логи можно и объединить

2024-02-18 14:46 UTC, SHvatov requested changes
@gavrilovds Дмитрий, и снова здравствуй! :)

You know the drill, оставил комментарии, жду правок) Буду вопросы по спрингу - пиши. И еще, создал новую группу для всяких там объявлений и тп - https://t.me/+KoDhaQZiHokwNDcy.

2024-02-18 15:07 UTC, gavrilovds commented on bot/src/main/java/edu/java/bot/message_sender/MessageSenderImpl.java
> +    private final LinkTrackerBot bot;
Да, здесь. Просто искал как это можно пофиксить, вот нашел решение через @Lazy. Поищу что-нибудь другое

2024-02-18 16:54 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/message_sender/MessageSenderImpl.java
> +    private final LinkTrackerBot bot;
@Lazy - хороший вариант для хотфикса, но не более. Можешь, пожалуйста, скинуть весь цикл, чтобы понимать, кто в него входит? Вообще стандартное решение - декомпозиция, вынесение какой-то части функциональности сервиса в новый.

2024-02-18 16:59 UTC, gavrilovds commented on bot/src/main/java/edu/java/bot/message_sender/MessageSenderImpl.java
> +    private final LinkTrackerBot bot;
<img width="175" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/d01fa125-a413-4140-82be-3b04ba7cd3d0">

2024-02-19 13:25 UTC, gavrilovds commented on bot/src/main/java/edu/java/bot/configuration/BotConfig.java
> +        return UpdateResolver.link(
<img width="741" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/0efab0e0-8ada-429f-a3c4-2958881f6fb8">
<img width="676" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/75f99fab-3325-4252-bad0-302fb65c871b">
<img width="524" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/e5c49bba-1f7f-4581-8cae-632fd5be47bc">

Как я понял, нужно написать что-то типо такого. Но опять получается циклическая зависимость. В список хочет заинжектиться сама цепочка, а не только реализации UpdateResolver`а. Или может какие-то еще варианты есть

2024-02-19 13:25 UTC, gavrilovds commented on bot/src/main/java/edu/java/bot/command/HelpCommandExecutor.java
> +        if (!command.equals(HELP.getCommandName())) {
Переделал

2024-02-24 12:25 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/BotConfig.java
> +        return UpdateResolver.link(
Необязательно придерживаться именно этого паттерна. Но в целом, есть очень распространённый паттерн manager / provider. Суть такова — ты заменяешь корневой резолвер на отдельный сервис-менеджер. В него инжектишь все резолверы, выстраиваешь из них иерархию и используешь как чейн. Вот и все)

2024-02-24 12:25 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/BotConfig.java
> +        return UpdateResolver.link(
Пока что давай оставим так, но потом, как-нибудь в рамках рефаторинга, можно будет попробовать это проверунть.

2024-02-24 12:26 UTC, SHvatov approved these changes
@gavrilovds ок, можно мержить)

2024-02-25 08:13 UTC, merged