Homework #2
gavrilovds/link-tracker pull request #2
Opened 2024-02-17 17:52 UTC by gavrilovds

2024-02-25 17:30 UTC, SHvatov requested changes
@gavrilovds оставил комментарии, посмотри их пожалуйста. Отдельный 👍 за клиентов!

2024-02-25 17:30 UTC, SHvatov commented on pom.xml
> +            <artifactId>netty-resolver-dns-native-macos</artifactId>
Небольшой коммент на будущее - эта зависимость нужна тебе только локально, на той же убунте все поднимется очень даже и без нее. Мы делаем в таких случаях очень просто - комментим такие зависимости или добавляем их только в `-dev` ветки. В данном случае зависимость можно и оставить.

2024-02-25 17:30 UTC, SHvatov commented on scrapper/src/main/java/edu/java/client/AbstractWebClient.java
> +    protected final HttpServiceProxyFactory factory;
Очень прикольная штука, не знал о ней 🔥

2024-02-25 17:30 UTC, SHvatov commented on scrapper/src/main/java/edu/java/client/AbstractWebClient.java
> +    protected final HttpServiceProxyFactory factory;
ИМХО, тут на твое усмотрение, но я бы сделал вот так:

```java
public abstract class AbstractWebClient<S> {

    protected final S service;

    @SuppressWarnings("unchecked")
    public AbstractWebClient(String baseUrl) {
        var factory = HttpServiceProxyFactory.builderFor(
            WebClientAdapter.create(
                WebClient.builder()
                    .baseUrl(baseUrl)
                    .build()
            )
        ).build();
        var serviceClass = (Class<S>) ((ParameterizedType) getClass().getGenericSuperclass())
            .getActualTypeArguments()[0];
        service = factory.createClient(serviceClass);
    }

}
```

И тогда тебе в под-классах вообще не нужно париться о создании сервиса :)

2024-02-25 17:30 UTC, SHvatov commented on scrapper/src/main/java/edu/java/client/github/GithubClient.java
> +    private static final String BASE_URL = "https://api.github.com/";
Урлы стоит вынести вынести в проперти. Да, локально ты можешь через wiremock замокать github, но очень часто такое еще тестируется реальными тестировщиками, а они любят использовать прокси, чтобы перехватывать запрос/ответ. И вот тут очень удобно держать урлы в пропертях. К примеру, на тестовом контуре ссылка на такую вот проксю, а на проде - на реальный гитхаб.

2024-02-25 17:30 UTC, SHvatov commented on scrapper/src/main/java/edu/java/client/link_information/LastUpdateTime.java
> +package edu.java.client.link_information;
`link_information` как-то слишком подробно для названия пакета. И вообще, я бы разделил клиенты и сервисы, которые обновляют время обновления страницы. Это разные сущности - одна чисто для того, чтобы делать запросы, другая имеет бизнесовую составляющую.

2024-02-25 17:30 UTC, SHvatov commented on scrapper/src/main/java/edu/java/client/link_information/LinkInformationReceiver.java
> +    @Autowired
Это, конечно, классический лайфхак, но в данном случае он избыточен. Просто в `LinkInformationReceiverProvider` в конструктор инжектишь все бины типа `LinkInformationReceiver`. И `LinkInformationReceiverProvider` -> `LinkInformationReceiverManager`, а `LinkInformationReceiver` -> `LinkInformationProvider`, что скажешь?

2024-02-25 17:30 UTC, SHvatov commented on scrapper/src/main/java/edu/java/client/link_information/LinkInformationReceiverProvider.java
> +        return receivers.getOrDefault(linkType, null);
Очень неочевидный интерфейс у метода. Если не хочешь кидать исключение, если тип ссылки не поддерживается, то лучше возвращать `Optional`, что даст клиентам твоего кода понять твои намерения.

2024-02-25 17:30 UTC, SHvatov commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    public LinkInformationReceiver stackOverflowClient() {
А чего бы сами сервисы не пометить как `Service`?

2024-02-25 17:34 UTC, SHvatov commented on scrapper/src/main/java/edu/java/client/github/GithubClient.java
> +    private static final String BASE_URL = "https://api.github.com/";
А, скузяо, не уивдел, что есть второй конструктор.

2024-02-25 18:10 UTC, gavrilovds commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    public LinkInformationReceiver stackOverflowClient() {
Имеется в виду `StackOverflowService` и `GithubService`? Если да, то я же их никуда не внедряю, а создаю сам через `HttpServiceProxyFactory`. Поэтому подумал, что аннотация избыточна была бы

2024-02-25 18:30 UTC, gavrilovds commented on scrapper/src/main/java/edu/java/client/link_information/LinkInformationReceiver.java
> +    @Autowired
Не знаю, правильно ли я понял, как именно это нужно сделать. Надеюсь да)

2024-02-25 18:35 UTC, gavrilovds commented on scrapper/src/main/java/edu/java/client/link_information/LinkInformationReceiver.java
> +    @Autowired
Или лучше вот так сделать:
```
@Component
public class LinkInformationReceiverManager {

    private final Map<LinkType, LinkInformationProvider> receivers = new HashMap<>();

    @Autowired
    public void registerReceivers(List<LinkInformationProvider> receiversList) {
        receiversList.forEach(receiver -> receivers.put(receiver.getLinkType(), receiver));
    }

    public Optional<LinkInformationProvider> getReceiver(LinkType linkType) {
        return Optional.ofNullable(receivers.get(linkType));
    }
}
```

2024-02-25 18:40 UTC, SHvatov commented on scrapper/src/main/java/edu/java/client/link_information/LinkInformationReceiver.java
> +    @Autowired
Все правильно понял, только лучше это все унести в конструктор. Вообще инициализация бинов через конструктор - наиболее хороший вариант.

2024-02-25 18:40 UTC, SHvatov commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    public LinkInformationReceiver stackOverflowClient() {
Я имел в виду клиенты сами - их пометить как компоненты.

2024-02-25 19:10 UTC, gavrilovds commented on scrapper/src/main/java/edu/java/configuration/ClientConfig.java
> +    public LinkInformationReceiver stackOverflowClient() {
Просто по заданию требовалось зарегистрировать клиентов как бины в отдельном config файле

2024-02-26 17:11 UTC, SHvatov approved these changes
@gavrilovds 🔥, можно мержить!

2024-02-26 18:44 UTC, merged