Homework #3
gavrilovds/link-tracker pull request #3
Opened 2024-02-23 17:39 UTC by gavrilovds

Такой вопросик, по заданию нужно было в дтошках для url искользовать класс URI. Это считается хорошей практикой? Просто как будто удобнее просто String использовать
### Сгенерированный Open API на localhost`e: 
<img width="1512" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/888be611-a600-40f0-be11-642a5e499662">
<img width="1512" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/44ecbbca-77cf-418c-b801-7489dd3b0d1b">

2024-03-05 14:19 UTC, SHvatov commented
> Такой вопросик, по заданию нужно было в дтошках для url искользовать класс URI. Это считается хорошей практикой? Просто как будто удобнее просто String использовать

Мы используем строку и не паримся. Не знаю точных причин, почему именно URI захотели использовать. Может как пример сериализации / десериализации.

2024-03-05 14:31 UTC, SHvatov requested changes
@gavrilovds оставил комментарии, посмотри их, пожалуйста.

2024-03-05 14:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/client/ScrapperClient.java
> +    private static final String BASE_URL = "http://localhost:8080/";
Такие дефолтные значения лучше держать на уровне конфига. Часто, для разработки, их вообще уносят в local.env файлы и используют вот такой плагин для запуска локально - https://plugins.jetbrains.com/plugin/7861-envfile. Еще один довод в пользу - так легко забыть прописать значение в конфиге, а потом на проде словить ошибки из-за того, что сервис посылает запросы на локалку.

2024-03-05 14:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/ClientConfig.java
> +        if (!scrapperBaseUrl.isEmpty()) {
Снова возвращаемся к предыдущему комментарию.

2024-03-05 14:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/StartCommandExecutor.java
> +        scrapperClient.registerChat(chatId);
Где-то выше по стеку есть обработка исключений от АПИ?

2024-03-05 14:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/UpdateService.java
> +
А можешь кратко описать что этот сервис будет делать? Кому будет отправлять апдейт, пользователю?

2024-03-05 14:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/update_resolver/CallbackUpdateResolver.java
> +        scrapperClient.untrackLink(chatId, new RemoveLinkRequest(Long.parseLong(data.split(":")[1])));
Часть со сплитом и кастом в лонг хорошо бы вынести и обработать, а то вдруг я передам `/untrack:someId`

2024-03-05 14:31 UTC, SHvatov commented on bot/src/main/resources/application.yml
> +    base-url:
вот сюда как раз и стоит унести дефолтное значение

2024-03-05 14:31 UTC, SHvatov commented on bot/src/test/java/edu/java/bot/command/UntrackCommandExecutorTest.java
> +    private ScrapperClient scrapperClient;
Новую строку бы для красоты

2024-03-05 14:31 UTC, SHvatov commented on scrapper/src/main/java/edu/java/controller/GlobalExceptionHandler.java
> +        return new ApiErrorResponse(
Не хочешь унести ApiErrorResponse в само исключение? Вроде как вся инфа для этого там есть.

2024-03-05 14:31 UTC, SHvatov commented on scrapper/src/main/java/edu/java/controller/GlobalExceptionHandler.java
> +        return new ApiErrorResponse(
И будет у тебя единая иерархия ошибок. Тогда хэндлер сокращается до обработки ApiErrorResponseException и получения ApiErrorResponse из него, а каждое исключение само решает, какой код ответа / сообщение для пользователя отдавать в АПИ.

2024-03-05 14:31 UTC, SHvatov commented on scrapper/src/main/java/edu/java/controller/GlobalExceptionHandler.java
> +            "409",
404, 409 - на это уже есть константы, стоит их использовать.

2024-03-05 14:31 UTC, SHvatov commented on scrapper/src/main/java/edu/java/controller/LinkController.java
> +    private static final String TG_CHAT_ID_HEADER = "Tg-Chat-Id";
А точно хочешь эту инфу пробрасывать через заголовки? Не по рестовому немного получается.

2024-03-05 14:36 UTC, gavrilovds commented on bot/src/main/java/edu/java/bot/service/UpdateService.java
> +
Да, будет пробегаться по айдишникам чатов из дто и отправлять сообщение об изменениях в отслеживаемой ссылке

2024-03-05 14:38 UTC, gavrilovds commented on bot/src/main/java/edu/java/bot/update_resolver/CallbackUpdateResolver.java
> +        scrapperClient.untrackLink(chatId, new RemoveLinkRequest(Long.parseLong(data.split(":")[1])));
А там нельзя самому ничего передать. Там в кнопку вшиваются данные на этапе построения клавиатуры

2024-03-05 14:39 UTC, gavrilovds commented on scrapper/src/main/java/edu/java/controller/LinkController.java
> +    private static final String TG_CHAT_ID_HEADER = "Tg-Chat-Id";
По open api просто вроде надо было пробрасывать chat id через хедер

2024-03-05 16:24 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/update_resolver/CallbackUpdateResolver.java
> +        scrapperClient.untrackLink(chatId, new RemoveLinkRequest(Long.parseLong(data.split(":")[1])));
я про `Long.parseLong(data.split(":")[1])`. Тут целых два кейса для обработки)

2024-03-05 16:24 UTC, SHvatov commented on scrapper/src/main/java/edu/java/controller/LinkController.java
> +    private static final String TG_CHAT_ID_HEADER = "Tg-Chat-Id";
Да, вижу. Тогда мое предложение - пойти против системы и сделать более рестово)

2024-03-05 16:27 UTC, gavrilovds commented on scrapper/src/main/java/edu/java/controller/LinkController.java
> +    private static final String TG_CHAT_ID_HEADER = "Tg-Chat-Id";
В дто тогда добавить айдишник чата?

2024-03-08 19:02 UTC, gavrilovds commented on bot/src/main/java/edu/java/bot/update_resolver/CallbackUpdateResolver.java
> +        scrapperClient.untrackLink(chatId, new RemoveLinkRequest(Long.parseLong(data.split(":")[1])));
Я все равно что-то не особо понял зачем тут обрабатывать, я же когда делаю /untrack, у меня вылезает клавиатура, на которой можно выбрать нужную ссылку. А данные для клавиши каждой ссылки забиваются в виде "/untrack:<id ссылки>", поэтому тут же всегда будут приходить корректные данные. Самому получается нельзя ничего передать.
<img width="851" alt="image" src="https://github.com/gavrilovds/link-tracker/assets/74236778/ddb224a3-144a-4359-bc4c-94759c185505">

2024-03-08 19:03 UTC, gavrilovds commented on scrapper/src/main/java/edu/java/controller/LinkController.java
> +    private static final String TG_CHAT_ID_HEADER = "Tg-Chat-Id";
Поменял

2024-03-08 19:05 UTC, gavrilovds commented on bot/src/main/java/edu/java/bot/command/StartCommandExecutor.java
> +        scrapperClient.registerChat(chatId);
Добавил обработку исключений. Только через http exchange не получается получить ApiErrorResponse, чтоб вытащить из него причину ошибки(. Поэтому просто отправляю пользователю сообщение о том, что произошла ошибка без указания причины

2024-03-11 20:15 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/StartCommandExecutor.java
> +        scrapperClient.registerChat(chatId);
Хм, я погляжу, как бы это можно было покрасивше реализовать (напомни плиз, если не отпишусь при проверке 4-ой ДЗ).

2024-03-11 20:15 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/update_resolver/CallbackUpdateResolver.java
> +        scrapperClient.untrackLink(chatId, new RemoveLinkRequest(Long.parseLong(data.split(":")[1])));
Если так, то ок)

2024-03-11 20:16 UTC, SHvatov approved these changes
@gavrilovds 🔥, 🚀

2024-03-12 16:50 UTC, merged